# Generated by Django 3.0.3 on 2020-02-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_cash_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='Data_date',
            field=models.DateTimeField(),
        ),
    ]
