# Generated by Django 3.0.2 on 2020-01-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_nation', models.CharField(max_length=50)),
                ('target_nation', models.CharField(max_length=50)),
                ('Data_date', models.DateField()),
                ('rate', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
